version: '3.8'

services:
  postgres:
    build:
      context: ..
      dockerfile: docker/dockerfile.postgres
    container_name: postgres-computer-vision-cats-dogs
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: computer-vision-cats-dogs
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data: